version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - testpackage
    - unconvert
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/alecthomas/assert
              desc: not allowed
            - pkg: github.com/magiconair/properties/assert
              desc: not allowed
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 200
      statements: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 30
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/jenkins-x/jx-logging/pkg/log/Logger()).Debugf
            - (github.com/jenkins-x/jx-logging/pkg/log/Logger()).Infof
            - (github.com/jenkins-x/jx-logging/pkg/log/Logger()).Warnf
            - (github.com/jenkins-x/jx-logging/pkg/log/Logger()).Errorf
            - (github.com/jenkins-x/jx-logging/pkg/log/Logger()).Fatalf
    lll:
      line-length: 140
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
      - linters:
          - testpackage
        path: _expansion_test\.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
