---
version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download

builds:
  - id: jv-linux
    main: ./cmd/jv/jv.go
    binary: jv
    ldflags:
      - -X github.com/jenkins-infra/jenkins-version/pkg/version.Version={{.Version}} -X github.com/jenkins-infra/jenkins-version/pkg/version.Revision={{.ShortCommit}} -X github.com/jenkins-infra/jenkins-version/pkg/version.BuildDate={{.CommitDate}} -X github.com/jenkins-infra/jenkins-version/pkg/version.BuiltBy=goreleaser
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x

  - id: jv-darwin
    main: ./cmd/jv/jv.go
    binary: jv
    ldflags:
      - -X github.com/jenkins-infra/jenkins-version/pkg/version.Version={{.Version}} -X github.com/jenkins-infra/jenkins-version/pkg/version.Revision={{.ShortCommit}} -X github.com/jenkins-infra/jenkins-version/pkg/version.BuildDate={{.CommitDate}} -X github.com/jenkins-infra/jenkins-version/pkg/version.BuiltBy=goreleaser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: jv-windows-amd64
    main: ./cmd/jv/jv.go
    binary: jv
    ldflags:
      - -X github.com/jenkins-infra/jenkins-version/pkg/version.Version={{.Version}} -X github.com/jenkins-infra/jenkins-version/pkg/version.Revision={{.ShortCommit}} -X github.com/jenkins-infra/jenkins-version/pkg/version.BuildDate={{.CommitDate}} -X github.com/jenkins-infra/jenkins-version/pkg/version.BuiltBy=goreleaser
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  disable: false

release:
  draft: false
  name_template: "{{.Tag}}"

brews:
  - name: jv
    repository:
      owner: jenkins-infra
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: jenkins-infra
      email: gareth@bryncynfelin.co.uk
    directory: Formula
    description: "Determine a Jenkins Version"
    homepage: https://github.com/jenkins-infra/jenkins-version
    install: |
      bin.install "jv"
