name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Test
        run: make test
